const API = 'API';
const SET_USER_INFO = 'SET_USER_INFO';
const TOGGLE_LOADING = 'TOGGLE_LOADING';
const RESET_USER_INFO= 'RESET_USER_INFO';

const SET_ALL_NOTES = 'SET_ALL_NOTES';
const ADD_NOTE = 'ADD_NOTE';
const REMOVE_NOTE = 'REMOVE_NOTE';
const UPDATE_NOTE = 'UPDATE_NOTE';

export default {
  API,
  SET_USER_INFO,
  TOGGLE_LOADING,
  RESET_USER_INFO,
  SET_ALL_NOTES,
  ADD_NOTE,
  REMOVE_NOTE,
  UPDATE_NOTE
}