const API = 'API';
const SET_USER_INFO = 'SET_USER_INFO';
const TOGGLE_LOADING = 'TOGGLE_LOADING';
const RESET_USER_INFO= 'RESET_USER_INFO';

export default {
  API,
  SET_USER_INFO,
  TOGGLE_LOADING,
  RESET_USER_INFO
}